In [14]:
# Import Library
import pandas as pd 

# Using readlines()

file1 = open('Charlotte_Roze_DM_Dic_Mod.dic', 'r')
Lines = file1.readlines()

#Extract the data from dic file and store it on List

List1=[]

for line in Lines:
    
    line = line.split(",")
    
    List1.append(line[0])

df_['Connector']= List1

In [15]:
df_

                      Connector
0                           ADN
1                       afin de
2                       afin d'
3                      afin que
4                       afin qu
..                          ...
754              et la marmotte
755                  et ta mère
756                  et ta sœur
757         et puis quoi encore
758  et mon cul c’est du poulet

[759 rows x 1 columns]

In [16]:
# Using readlines()

file1 = open('Dela_fr_alternative.dic', 'r')
Lines = file1.readlines()

# Create Dataframe to hold the connectors

columns = ['Connector','code']
df2_ = pd.DataFrame(columns=columns)

List2=[]
code=[]
#Extract the data from txt file and store it on Dataframe
for line in Lines:
    line1 = line.split(",")
    line2 = line1[1].split(".")
    List2.append(line1[0])
    List2.append(line2[0])
    code.append(line2[1])
    code.append(line2[1])
df2_['Connector']= List2
df2_['code']= code

In [17]:
df2_

        Connector              code
0             ADN     OTHER:ms:mp\n
1                     OTHER:ms:mp\n
2             ARN     OTHER:ms:mp\n
3                     OTHER:ms:mp\n
4            ARNm     OTHER:ms:mp\n
...           ...               ...
1684865            OTHER+z3:ms:mp\n
1684866         û  OTHER+z1:ms:mp\n
1684867            OTHER+z1:ms:mp\n
1684868         ü  OTHER+z1:ms:mp\n
1684869            OTHER+z1:ms:mp\n

[1684870 rows x 2 columns]

In [22]:
df2_['Connector'].replace('', np.nan, inplace=True)# change the space value by nan value

df2_.dropna(subset=['Connector'], inplace=True)# Drop the the rows that hold nan value

df2_.reset_index(drop=True, inplace=True)# re-organize the index value

In [23]:
df2_

        Connector              code
0             ADN     OTHER:ms:mp\n
1             ARN     OTHER:ms:mp\n
2            ARNm     OTHER:ms:mp\n
3            ARNr     OTHER:ms:mp\n
4            ARNs     OTHER:ms:mp\n
...           ...               ...
1494164       ôté     OTHER+z1:mp\n
1494165         ö  OTHER+z1:ms:mp\n
1494166       öre  OTHER+z3:ms:mp\n
1494167         û  OTHER+z1:ms:mp\n
1494168         ü  OTHER+z1:ms:mp\n

[1494169 rows x 2 columns]

In [24]:
for value in con1:
      for i in range(len(df2_)):
            if (value == df2_['Connector'][i]) and 'OTHER+' in df2_['code'][i]: # test if the DM is Other
                print(value)

afin de
au lieu de
au lieu de
au lieu de
au moment de
au moment de
au moment de
au point de
au point de
au point de
avant
avant
avant
avant de
avant de
avant de
bref
bref
bref
bref
bref
bref
car
car
d'ailleurs
dans l'espoir de
dans l'espoir de
dans l'espoir de
dans l'intention de
dans l'intention de
dans l'intention de
dans le but de
dans le but de
dans le but de
en
en dépit de
en dépit de
en dépit de
en plus de
en plus de
en plus de
en vue de
en vue de
en vue de
faute de
faute de
faute de
histoire de
histoire de
histoire de
maintenant
mais
mieux
même
même
or
or
pour
puis
quant à
quant à
remarque
remarque
remarque
résultat
résultat
si
soit
soudain
soudain
soudain
soudain
surtout
surtout
total
total
total
total
total
total
à condition de
à condition de
à condition de
à défaut de
à défaut de
à défaut de
à force de
à force de
à force de
à moins de
à moins de
à moins de
à seule fin de
à seule fin de
à seule fin de
à mesure de
à mesure de
à mesure de
attendu
attendu
attendu
attendu
attendu
attendu
attendu
au fur et à mesure de
au fur et à mesure de
au fur et à mesure de
considérant
considérant
considérant
considéré
du fait de
du fait de
du fait de
le temps de
le temps de
le temps de
pendant
pendant
pendant
pendant
pendant
pendant
pendant
chic
chic
chic
chic
chiche
chiche
bon
bon
bon
bon
bon
bon
bon
bon
bien
bien
bien
comment
hélas
non
oui
mais
amen
bernique
bernique
bravo
bravo
chut
crac
crac
haha
heu
heu
ho
holà
hourra
hourra
hum
hum
ouille
paf
adieu
adieu
attention
attention
banco
banco
bingo
bingo
bonjour
bonjour
bonsoir
bonsoir
bonté
bonté
bordel
bordel
bougre
bougre
bougre
bougre
camembert
camembert
catastrophe
catastrophe
catastrophe
ciel
ciel
ciel
chapeau
chapeau
chiotte
chiotte
con
con
con
con
con
con
con
con
courage
courage
crotte
crotte
crotte
dame
dame
dame
diable
diable
diable
diable
diable
diable
dommage
dommage
grâce
grâce
flûte
flûte
flûte
halte
halte
halte
malheur
malheur
merci
merci
merci
merde
merde
merde
misère
misère
pardon
pardon
pétard
pétard
pitié
pitié
prout
prout
punaise
punaise
punaise
punaise
purée
purée
putain
putain
putain
putain
quoi
respect
respect
salut
salut
santé
santé
seigneur
seigneur
stop
stop
tralala
tralala
tonnerre
tonnerre
nom de Dieu
bon Dieu
au revoir
admettons
allons
allez
dis
dites
dites
disons
écoute
écoute
écoute
écoutez
regarde
regardez
remarque
remarque
remarque
remarquez
tiens
tiens
tiens
tenez
va
voyez
voyons
soit
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre
foutre